"""text

Revision ID: 4a2e82812f64
Revises: a739ae0b9a25
Create Date: 2025-03-13 16:41:41.162031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2e82812f64'
down_revision: Union[str, None] = 'a739ae0b9a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_suites', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_suites', 'test_projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_suites', type_='foreignkey')
    op.drop_column('test_suites', 'project_id')
    # ### end Alembic commands ###
