"""text

Revision ID: a739ae0b9a25
Revises: 7d90d1814c4a
Create Date: 2025-03-10 16:07:14.968727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a739ae0b9a25'
down_revision: Union[str, None] = '7d90d1814c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_projects_id'), 'test_projects', ['id'], unique=False)
    op.create_index(op.f('ix_test_projects_project_name'), 'test_projects', ['project_name'], unique=True)
    op.create_table('user_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['test_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.add_column('test_reports', sa.Column('test_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_reports', 'test_projects', ['test_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_reports', type_='foreignkey')
    op.drop_column('test_reports', 'test_project_id')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_test_projects_project_name'), table_name='test_projects')
    op.drop_index(op.f('ix_test_projects_id'), table_name='test_projects')
    op.drop_table('test_projects')
    # ### end Alembic commands ###
